openapi: 3.2.0
info:
  title: Complete InfluxDB Cloud Organizations API
  description: 'Manage your organization.

    An organization is a workspace for a group of users. Organizations can be

    used to separate different environments, projects, teams or users within

    InfluxDB.


    Use the `/api/v2/orgs` endpoints to view and manage organizations.'
servers:
- url: ''
security:
- TokenAuthentication: []
tags:
- description: 'Manage your organization.

    An organization is a workspace for a group of users. Organizations can be

    used to separate different environments, projects, teams or users within

    InfluxDB.


    Use the `/api/v2/orgs` endpoints to view and manage organizations.'
  name: Organizations
paths:
  /api/v2/orgs:
    get:
      description: 'Lists organizations.


        To limit which organizations are returned, pass query parameters in your request.

        If no query parameters are passed, InfluxDB returns all organizations up to the default `limit`.


        #### InfluxDB Cloud


        - Only returns the organization that owns the token passed in the request.


        #### Related guides


        - View organizations'
      operationId: GetOrgs
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - $ref: '#/components/parameters/Offset'
      - $ref: '#/components/parameters/Limit'
      - $ref: '#/components/parameters/Descending'
      - description: 'An organization name.

          Only returns the specified organization.

          '
        in: query
        name: org
        schema:
          type: string
      - description: 'An organization ID.

          Only returns the specified organization.

          '
        in: query
        name: orgID
        schema:
          type: string
      - description: 'A user ID.

          Only returns organizations where the specified user is a member or owner.

          '
        in: query
        name: userID
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                successResponse:
                  value:
                    links:
                      self: /api/v2/orgs
                    orgs:
                    - createdAt: '2022-07-17T23:00:30.778487Z'
                      description: Example InfluxDB organization
                      id: INFLUX_ORG_ID
                      links:
                        buckets: /api/v2/buckets?org=INFLUX_ORG
                        dashboards: /api/v2/dashboards?org=INFLUX_ORG
                        labels: /api/v2/orgs/INFLUX_ORG_ID/labels
                        logs: /api/v2/orgs/INFLUX_ORG_ID/logs
                        members: /api/v2/orgs/INFLUX_ORG_ID/members
                        owners: /api/v2/orgs/INFLUX_ORG_ID/owners
                        secrets: /api/v2/orgs/INFLUX_ORG_ID/secrets
                        self: /api/v2/orgs/INFLUX_ORG_ID
                        tasks: /api/v2/tasks?org=InfluxData
                      name: INFLUX_ORG
                      updatedAt: '2022-07-17T23:00:30.778487Z'
              schema:
                $ref: '#/components/schemas/Organizations'
          description: Success. The response body contains a list of organizations.
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/GeneralServerError'
      summary: List organizations
      tags:
      - Organizations
    post:
      description: 'Creates an organization

        and returns the newly created organization.


        #### InfluxDB Cloud


        - Doesn''t allow you to use this endpoint to create organizations.


        #### Related guides


        - Manage organizations'
      operationId: PostOrgs
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostOrganizationRequest'
        description: The organization to create.
        required: true
      responses:
        '201':
          content:
            application/json:
              examples:
                successResponse:
                  value:
                    createdAt: '2022-08-24T23:05:52.881317Z'
                    description: ''
                    id: INFLUX_ORG_ID
                    links:
                      buckets: /api/v2/buckets?org=INFLUX_ORG
                      dashboards: /api/v2/dashboards?org=INFLUX_ORG
                      labels: /api/v2/orgs/INFLUX_ORG_ID/labels
                      logs: /api/v2/orgs/INFLUX_ORG_ID/logs
                      members: /api/v2/orgs/INFLUX_ORG_ID/members
                      owners: /api/v2/orgs/INFLUX_ORG_ID/owners
                      secrets: /api/v2/orgs/INFLUX_ORG_ID/secrets
                      self: /api/v2/orgs/INFLUX_ORG_ID
                      tasks: /api/v2/tasks?org=INFLUX_ORG
                    name: INFLUX_ORG
                    updatedAt: '2022-08-24T23:05:52.881318Z'
              schema:
                $ref: '#/components/schemas/Organization'
          description: Created. The response body contains the organization information.
        '400':
          $ref: '#/components/responses/BadRequestError'
          examples:
            invalidRequest:
              summary: The `name` field is missing from the request body.
              value:
                code: invalid
                message: org name is empty
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Create an organization
      tags:
      - Organizations
      x-codeSamples:
      - label: cURL
        lang: Shell
        source: "curl --request POST \"http://localhost:8086/api/v2/orgs \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --header \"Accept: application/json\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n      \"name\": \"INFLUX_ORG\",\n      \"description: \"Example InfluxDB organization\"\n    }'\n"
  /api/v2/orgs/{orgID}:
    delete:
      description: 'Deletes an organization.


        Deleting an organization from InfluxDB Cloud can''t be undone.

        Once deleted, all data associated with the organization is removed.


        #### InfluxDB Cloud


        - Does the following when you send a delete request:


        1. Validates the request and queues the delete.

        2. Returns an HTTP `204` status code if queued; _error_ otherwise.

        3. Handles the delete asynchronously.


        #### InfluxDB OSS


        - Validates the request, handles the delete synchronously,

        and then responds with success or failure.


        #### Limitations


        - Only one organization can be deleted per request.


        #### Related guides


        - Delete organizations'
      operationId: DeleteOrgsID
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: 'The ID of the organization to delete.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: "Success.\n\n#### InfluxDB Cloud\n  - The organization is queued for deletion.\n\n#### InfluxDB OSS\n  - The organization is deleted.\n"
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          content:
            application/json:
              examples:
                notFound:
                  summary: 'The requested organization was not found.

                    '
                  value:
                    code: not found
                    message: org not found
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Not found.

            InfluxDB can''t find the organization.

            '
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Delete an organization
      tags:
      - Organizations
    get:
      description: 'Retrieves an organization.


        Use this endpoint to retrieve information for a specific organization.


        #### Related guides


        - View organizations'
      operationId: GetOrgsID
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: 'The ID of the organization to retrieve.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
          description: 'Success.

            The response body contains the organization information.

            '
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          content:
            application/json:
              examples:
                notFound:
                  summary: 'The requested organization wasn''t found.

                    '
                  value:
                    code: not found
                    message: organization not found
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Not found.

            Organization not found.

            '
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Retrieve an organization
      tags:
      - Organizations
    patch:
      description: 'Updates an organization.


        Use this endpoint to update properties

        (`name`, `description`) of an organization.


        Updating an organization’s name affects all resources that reference the

        organization by name, including the following:


        - Queries

        - Dashboards

        - Tasks

        - Telegraf configurations

        - Templates


        If you change an organization name, be sure to update the organization name

        in these resources as well.


        #### Related Guides


        - Update an organization'
      operationId: PatchOrgsID
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: 'The ID of the organization to update.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchOrganizationRequest'
        description: The organization update to apply.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
          description: Success. The response body contains the updated organization.
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Update an organization
      tags:
      - Organizations
  /api/v2/orgs/{orgID}/members:
    get:
      description: 'Lists all users that belong to an organization.


        InfluxDB users have

        permission to access InfluxDB.


        Members are users

        within the organization.


        #### InfluxDB Cloud


        - Doesn''t use `owner` and `member` roles.

        Use `/api/v2/authorizations`) to assign user permissions.


        #### Limitations


        - Member permissions are separate from API token permissions.

        - Member permissions are used in the context of the InfluxDB UI.


        #### Required permissions


        - `read-orgs INFLUX_ORG_ID`


        *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve

        members for.


        #### Related guides


        - Manage users

        - Manage members'
      operationId: GetOrgsIDMembers
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: 'The ID of the organization to retrieve users for.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                successResponse:
                  value:
                    links:
                      self: /api/v2/orgs/055aa4783aa38398/members
                    users:
                    - id: 791df274afd48a83
                      links:
                        self: /api/v2/users/791df274afd48a83
                      name: example_user_1
                      role: member
                      status: active
                    - id: 09cfb87051cbe000
                      links:
                        self: /api/v2/users/09cfb87051cbe000
                      name: example_user_2
                      role: owner
                      status: active
              schema:
                $ref: '#/components/schemas/ResourceMembers'
          description: 'Success.

            The response body contains a list of all users within the organization.

            '
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          content:
            application/json:
              examples:
                notFound:
                  summary: 'The requested organization wasn''t found.

                    '
                  value:
                    code: not found
                    message: 404 page not found
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Not found.

            InfluxDB can''t find the organization.

            '
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: List all members of an organization
      tags:
      - Organizations
    post:
      description: 'Add a user to an organization.


        InfluxDB users have

        permission to access InfluxDB.


        Members are users

        within the organization.


        #### InfluxDB Cloud

        - Doesn''t use `owner` and `member` roles.

        Use `/api/v2/authorizations`) to assign user permissions.


        #### Limitations


        - Member permissions are separate from API token permissions.

        - Member permissions are used in the context of the InfluxDB UI.


        #### Required permissions


        - `write-orgs INFLUX_ORG_ID`


        *`INFLUX_ORG_ID`* is the ID of the organization that you want to add a member to.


        #### Related guides


        - Manage users

        - Manage members'
      operationId: PostOrgsIDMembers
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: 'The ID of the organization.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddResourceMemberRequestBody'
        description: 'The user to add to the organization.

          '
        required: true
      responses:
        '201':
          content:
            application/json:
              examples:
                successResponse:
                  value:
                    id: 09cfb87051cbe000
                    links:
                      self: /api/v2/users/09cfb87051cbe000
                    name: example_user_1
                    role: member
                    status: active
              schema:
                $ref: '#/components/schemas/ResourceMember'
          description: 'Success.

            The response body contains the user information.

            '
        '400':
          $ref: '#/components/responses/BadRequestError'
          examples:
            invalidRequest:
              summary: The user `id` is missing from the request body.
              value:
                code: invalid
                message: user id missing or invalid
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Add a member to an organization
      tags:
      - Organizations
      x-codeSamples:
      - label: cURL
        lang: Shell
        source: "curl --request POST \"http://localhost:8086/api/v2/orgs/INFLUX_ORG_ID/members \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --header \"Accept: application/json\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n      \"id\": \"09cfb87051cbe000\"\n    }'\n"
  /api/v2/orgs/{orgID}/members/{userID}:
    delete:
      description: 'Removes a member from an organization.


        Use this endpoint to remove a user''s member privileges for an organization.

        Removing member privileges removes the user''s `read` and `write` permissions

        from the organization.


        #### InfluxDB Cloud


        - Doesn''t use `owner` and `member` roles.

        Use `/api/v2/authorizations`) to assign user permissions.


        #### Limitations


        - Member permissions are separate from API token permissions.

        - Member permissions are used in the context of the InfluxDB UI.


        #### Required permissions


        - `write-orgs INFLUX_ORG_ID`


        *`INFLUX_ORG_ID`* is the ID of the organization that you want to remove an

        owner from.


        #### Related guides


        - Manage members'
      operationId: DeleteOrgsIDMembersID
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: The ID of the user to remove.
        in: path
        name: userID
        required: true
        schema:
          type: string
      - description: The ID of the organization to remove a user from.
        in: path
        name: orgID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: 'Success.

            The user is no longer a member of the organization.

            '
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Remove a member from an organization
      tags:
      - Organizations
  /api/v2/orgs/{orgID}/owners:
    get:
      description: 'Lists all owners of an organization.


        #### InfluxDB Cloud


        - Doesn''t use `owner` and `member` roles.

        Use `/api/v2/authorizations`) to assign user permissions.


        #### Required permissions


        - `read-orgs INFLUX_ORG_ID`


        *`INFLUX_ORG_ID`* is the ID of the organization that you want to retrieve a

        list of owners from.'
      operationId: GetOrgsIDOwners
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: 'The ID of the organization to list owners for.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                successResponse:
                  value:
                    links:
                      self: /api/v2/orgs/055aa4783aa38398/owners
                    users:
                    - id: 09cfb87051cbe000
                      links:
                        self: /api/v2/users/09cfb87051cbe000
                      name: example_user_2
                      role: owner
                      status: active
              schema:
                $ref: '#/components/schemas/ResourceOwners'
          description: A list of organization owners
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Organization not found
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: List all owners of an organization
      tags:
      - Organizations
    post:
      description: 'Adds an owner to an organization.


        Use this endpoint to assign the organization `owner` role to a user.


        #### InfluxDB Cloud


        - Doesn''t use `owner` and `member` roles.

        Use `/api/v2/authorizations`) to assign user permissions.


        #### Required permissions


        - `write-orgs INFLUX_ORG_ID`


        *`INFLUX_ORG_ID`* is the ID of the organization that you want to add an owner for.


        #### Related endpoints


        - Authorizations)'
      operationId: PostOrgsIDOwners
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: The ID of the organization that you want to add an owner for.
        in: path
        name: orgID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            examples:
              successResponse:
                value:
                  id: 09cfb87051cbe000
                  links:
                    self: /api/v2/users/09cfb87051cbe000
                  name: example_user_1
                  role: owner
                  status: active
            schema:
              $ref: '#/components/schemas/AddResourceMemberRequestBody'
        description: The user to add as an owner of the organization.
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceOwner'
          description: 'Success. The user is an owner of the organization.

            The response body contains the owner with role and user detail.

            '
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Add an owner to an organization
      tags:
      - Organizations
      x-codeSamples:
      - label: cURL
        lang: Shell
        source: "curl --request POST \"http://localhost:8086/api/v2/orgs/INFLUX_ORG_ID/owners \\\n  --header \"Authorization: Token INFLUX_API_TOKEN\" \\\n  --header \"Accept: application/json\" \\\n  --header \"Content-Type: application/json\" \\\n  --data '{\n      \"id\": \"09cfb87051cbe000\"\n    }'\n"
  /api/v2/orgs/{orgID}/owners/{userID}:
    delete:
      description: 'Removes an owner from

        the organization.


        Organization owners have permission to delete organizations and remove user and member

        permissions from the organization.


        #### InfluxDB Cloud

        - Doesn''t use `owner` and `member` roles.

        Use `/api/v2/authorizations`) to assign user permissions.


        #### Limitations


        - Owner permissions are separate from API token permissions.

        - Owner permissions are used in the context of the InfluxDB UI.


        #### Required permissions


        - `write-orgs INFLUX_ORG_ID`


        *`INFLUX_ORG_ID`* is the ID of the organization that you want to

        remove an owner from.


        #### Related endpoints

        - Authorizations)'
      operationId: DeleteOrgsIDOwnersID
      parameters:
      - $ref: '#/components/parameters/TraceSpan'
      - description: The ID of the user to remove.
        in: path
        name: userID
        required: true
        schema:
          type: string
      - description: 'The ID of the organization to remove an owner from.

          '
        in: path
        name: orgID
        required: true
        schema:
          type: string
      responses:
        '204':
          description: 'Success.

            The user is no longer an owner of the organization.

            '
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/ResourceNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Remove an owner from an organization
      tags:
      - Organizations
components:
  responses:
    BadRequestError:
      content:
        application/json:
          examples:
            orgProvidedNotFound:
              summary: The org or orgID passed doesn't own the token passed in the header
              value:
                code: invalid
                message: 'failed to decode request body: organization not found'
          schema:
            $ref: '#/components/schemas/Error'
      description: 'Bad request.

        The response body contains detail about the error.


        #### InfluxDB OSS


        - Returns this error if an incorrect value is passed in the `org` parameter or `orgID` parameter.

        '
    ResourceNotFoundError:
      content:
        application/json:
          examples:
            bucket-not-found:
              summary: Bucket name not found
              value:
                code: not found
                message: bucket "air_sensor" not found
            org-not-found:
              summary: Organization name not found
              value:
                code: not found
                message: organization name "my-org" not found
            orgID-not-found:
              summary: Organization ID not found
              value:
                code: not found
                message: organization not found
          schema:
            $ref: '#/components/schemas/Error'
      description: "Not found.\nA requested resource was not found.\nThe response body contains the requested resource type and the name value\n(if you passed it)--for example:\n\n- `\"organization name \\\"my-org\\\" not found\"`\n- `\"organization not found\"`: indicates you passed an ID that did not match\n   an organization.\n"
    InternalServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: 'Internal server error.

        The server encountered an unexpected situation.

        '
    GeneralServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Non 2XX error response from server.
    AuthorizationError:
      content:
        application/json:
          examples:
            tokenNotAuthorized:
              summary: Token is not authorized to access a resource
              value:
                code: unauthorized
                message: unauthorized access
          schema:
            properties:
              code:
                description: 'The HTTP status code description. Default is `unauthorized`.

                  '
                enum:
                - unauthorized
                readOnly: true
                type: string
              message:
                description: A human-readable message that may contain detail about the error.
                readOnly: true
                type: string
      description: "Unauthorized. The error may indicate one of the following:\n\n  * The `Authorization: Token` header is missing or malformed.\n  * The API token value is missing from the header.\n  * The token doesn't have sufficient permissions to write to this organization and bucket.\n"
  schemas:
    ErrorCode:
      description: code is the machine-readable error code.
      enum:
      - internal error
      - not implemented
      - not found
      - conflict
      - invalid
      - unprocessable entity
      - empty value
      - unavailable
      - forbidden
      - too many requests
      - unauthorized
      - method not allowed
      - request too large
      - unsupported media type
      readOnly: true
      type: string
    UserResponse:
      properties:
        id:
          description: 'The user ID.

            '
          readOnly: true
          type: string
        links:
          example:
            self: /api/v2/users/1
          properties:
            self:
              format: uri
              type: string
          readOnly: true
          type: object
        name:
          description: 'The user name.

            '
          type: string
        status:
          default: active
          description: 'The status of a user.

            An inactive user can''t read or write resources.

            '
          enum:
          - active
          - inactive
          type: string
      required:
      - name
    PostOrganizationRequest:
      properties:
        description:
          description: 'The description of the organization.

            '
          type: string
        name:
          description: 'The name of the organization.

            '
          type: string
      required:
      - name
      type: object
    Link:
      description: URI of resource.
      format: uri
      readOnly: true
      type: string
    Links:
      description: 'URI pointers for additional paged results.

        '
      properties:
        next:
          $ref: '#/components/schemas/Link'
        prev:
          $ref: '#/components/schemas/Link'
        self:
          $ref: '#/components/schemas/Link'
      required:
      - self
      type: object
    Organization:
      properties:
        createdAt:
          format: date-time
          readOnly: true
          type: string
        defaultStorageType:
          description: Discloses whether the organization uses TSM or IOx.
          enum:
          - tsm
          - iox
          type: string
        description:
          type: string
        id:
          readOnly: true
          type: string
        links:
          example:
            buckets: /api/v2/buckets?org=myorg
            dashboards: /api/v2/dashboards?org=myorg
            labels: /api/v2/orgs/1/labels
            members: /api/v2/orgs/1/members
            owners: /api/v2/orgs/1/owners
            secrets: /api/v2/orgs/1/secrets
            self: /api/v2/orgs/1
            tasks: /api/v2/tasks?org=myorg
          properties:
            buckets:
              $ref: '#/components/schemas/Link'
            dashboards:
              $ref: '#/components/schemas/Link'
            labels:
              $ref: '#/components/schemas/Link'
            members:
              $ref: '#/components/schemas/Link'
            owners:
              $ref: '#/components/schemas/Link'
            secrets:
              $ref: '#/components/schemas/Link'
            self:
              $ref: '#/components/schemas/Link'
            tasks:
              $ref: '#/components/schemas/Link'
          readOnly: true
          type: object
        name:
          type: string
        status:
          default: active
          description: If inactive, the organization is inactive.
          enum:
          - active
          - inactive
          type: string
        updatedAt:
          format: date-time
          readOnly: true
          type: string
      required:
      - name
    ResourceMembers:
      properties:
        links:
          properties:
            self:
              format: uri
              type: string
          type: object
        users:
          items:
            $ref: '#/components/schemas/ResourceMember'
          type: array
      type: object
    AddResourceMemberRequestBody:
      properties:
        id:
          description: 'The ID of the user to add to the resource.

            '
          type: string
        name:
          description: 'The name of the user to add to the resource.

            '
          type: string
      required:
      - id
      type: object
    Error:
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
          description: code is the machine-readable error code.
          enum:
          - internal error
          - not implemented
          - not found
          - conflict
          - invalid
          - unprocessable entity
          - empty value
          - unavailable
          - forbidden
          - too many requests
          - unauthorized
          - method not allowed
          - request too large
          - unsupported media type
          readOnly: true
          type: string
        err:
          description: Stack of errors that occurred during processing of the request. Useful for debugging.
          readOnly: true
          type: string
        message:
          description: Human-readable message.
          readOnly: true
          type: string
        op:
          description: Describes the logical code operation when the error occurred. Useful for debugging.
          readOnly: true
          type: string
      required:
      - code
    ResourceOwner:
      allOf:
      - $ref: '#/components/schemas/UserResponse'
      - properties:
          role:
            default: owner
            enum:
            - owner
            type: string
        type: object
    Organizations:
      properties:
        links:
          $ref: '#/components/schemas/Links'
        orgs:
          items:
            $ref: '#/components/schemas/Organization'
          type: array
      type: object
    PatchOrganizationRequest:
      description: 'An object that contains updated organization properties to apply.

        '
      properties:
        description:
          description: 'The description of the organization.

            '
          type: string
        name:
          description: 'The name of the organization.

            '
          type: string
      type: object
    ResourceMember:
      allOf:
      - $ref: '#/components/schemas/UserResponse'
      - properties:
          role:
            default: member
            enum:
            - member
            type: string
        type: object
    ResourceOwners:
      properties:
        links:
          properties:
            self:
              format: uri
              type: string
          type: object
        users:
          items:
            $ref: '#/components/schemas/ResourceOwner'
          type: array
      type: object
  parameters:
    Limit:
      description: 'Limits the number of records returned. Default is `20`.

        '
      in: query
      name: limit
      required: false
      schema:
        default: 20
        maximum: 100
        minimum: 1
        type: integer
    Descending:
      in: query
      name: descending
      required: false
      schema:
        default: false
        type: boolean
    Offset:
      description: 'The offset for pagination.

        The number of records to skip.


        For more information about pagination parameters, see [Pagination](https://docs.influxdata.com/influxdb/cloud/api/#tag/Pagination).

        '
      in: query
      name: offset
      required: false
      schema:
        minimum: 0
        type: integer
    TraceSpan:
      description: OpenTracing span context
      example:
        baggage:
          key: value
        span_id: '1'
        trace_id: '1'
      in: header
      name: Zap-Trace-Span
      required: false
      schema:
        type: string
  securitySchemes:
    BasicAuthentication:
      description: "### Basic authentication scheme\n\nUse the HTTP Basic authentication scheme for InfluxDB `/api/v2` API operations that support it:\n\n### Syntax\n\n`Authorization: Basic BASE64_ENCODED_CREDENTIALS`\n\nTo construct the `BASE64_ENCODED_CREDENTIALS`, combine the username and\nthe password with a colon (`USERNAME:PASSWORD`), and then encode the\nresulting string in [base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64).\nMany HTTP clients encode the credentials for you before sending the\nrequest.\n\n_**Warning**: Base64-encoding can easily be reversed to obtain the original\nusername and password. It is used to keep the data intact and does not provide\nsecurity. You should always use HTTPS when authenticating or sending a request with\nsensitive information._\n\n### Examples\n\nIn the examples, replace the following:\n\n- **`EMAIL_ADDRESS`**: InfluxDB Cloud username (the email address the user signed up with)\n- **`PASSWORD`**: InfluxDB Cloud [API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n- **`INFLUX_URL`**: your InfluxDB Cloud URL\n\n#### Encode credentials with cURL\n\nThe following example shows how to use cURL to send an API request that uses Basic authentication.\nWith the `--user` option, cURL encodes the credentials and passes them\nin the `Authorization: Basic` header.\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --user \"EMAIL_ADDRESS\":\"PASSWORD\"\n```\n\n#### Encode credentials with Flux\n\nThe Flux [`http.basicAuth()` function](https://docs.influxdata.com/flux/v0.x/stdlib/http/basicauth/) returns a Base64-encoded\nbasic authentication header using a specified username and password combination.\n\n#### Encode credentials with JavaScript\n\nThe following example shows how to use the JavaScript `btoa()` function\nto create a Base64-encoded string:\n\n```js\nbtoa('EMAIL_ADDRESS:PASSWORD')\n```\n\nThe output is the following:\n\n```js\n'VVNFUk5BTUU6UEFTU1dPUkQ='\n```\n\nOnce you have the Base64-encoded credentials, you can pass them in the\n`Authorization` header--for example:\n\n```sh\ncurl --get \"INFLUX_URL/api/v2/signin\"\n    --header \"Authorization: Basic VVNFUk5BTUU6UEFTU1dPUkQ=\"\n```\n\nTo learn more about HTTP authentication, see\n[Mozilla Developer Network (MDN) Web Docs, HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)._\n"
      scheme: basic
      type: http
    TokenAuthentication:
      description: "Use the [Token authentication](#section/Authentication/TokenAuthentication)\nscheme to authenticate to the InfluxDB API.\n\nIn your API requests, send an `Authorization` header.\nFor the header value, provide the word `Token` followed by a space and an InfluxDB API token.\nThe word `Token` is case-sensitive.\n\n### Syntax\n\n`Authorization: Token INFLUX_API_TOKEN`\n\n### Example\n\n#### Use Token authentication with cURL\n\nThe following example shows how to use cURL to send an API request that uses Token authentication:\n\n```sh\ncurl --request GET \"INFLUX_URL/api/v2/buckets\" \\\n     --header \"Authorization: Token INFLUX_API_TOKEN\"\n```\n\nReplace the following:\n\n  - *`INFLUX_URL`*: your InfluxDB Cloud URL\n  - *`INFLUX_API_TOKEN`*: your [InfluxDB API token](https://docs.influxdata.com/influxdb/cloud/reference/glossary/#token)\n\n### Related endpoints\n\n- [`/authorizations` endpoints](#tag/Authorizations-(API-tokens))\n\n### Related guides\n\n- [Authorize API requests](https://docs.influxdata.com/influxdb/cloud/api-guide/api_intro/#authentication)\n- [Manage API tokens](https://docs.influxdata.com/influxdb/cloud/security/tokens/)\n"
      in: header
      name: Authorization
      type: apiKey
x-tagGroups:
- name: Overview
  tags:
  - Quick start
  - Authentication
  - Supported operations
  - Headers
  - Pagination
  - Response codes
- name: Popular endpoints
  tags:
  - Data I/O endpoints
  - Security and access endpoints
  - System information endpoints
- name: All endpoints
  tags: []
